
package com.ug.vista;

import java.awt.Color;

/**
 *
 * @author Luis
 */
public class FrmMainMenu extends javax.swing.JDialog {

    /**
     * Creates new form FrmMainMenu
     */
    public FrmMainMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sideMenuBg = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JPanel();
        btnCerrarSesionTxt = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JPanel();
        btnUsuarioTxt = new javax.swing.JLabel();
        btnMateria = new javax.swing.JPanel();
        btnMateriaTxt = new javax.swing.JLabel();
        btnTarea = new javax.swing.JPanel();
        btnTareaTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgUserData = new javax.swing.JPanel();
        nombreTitleTxt = new javax.swing.JLabel();
        txtRol = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtApellidos = new javax.swing.JLabel();
        apellidosTitleTxt = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtCedula = new javax.swing.JLabel();
        cedulaTitleTxt = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JLabel();
        correoTitleTxt = new javax.swing.JLabel();
        txtNombres1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideMenuBg.setBackground(new java.awt.Color(62, 88, 121));
        sideMenuBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setBackground(new java.awt.Color(157, 179, 204));

        btnCerrarSesionTxt.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnCerrarSesionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesionTxt.setText("Cerrar sesión");
        btnCerrarSesionTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSesionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sideMenuBg.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 415, -1, -1));

        btnUsuario.setBackground(new java.awt.Color(157, 179, 204));

        btnUsuarioTxt.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnUsuarioTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUsuarioTxt.setText("Usuario");
        btnUsuarioTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuarioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuarioTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuarioTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUsuarioLayout = new javax.swing.GroupLayout(btnUsuario);
        btnUsuario.setLayout(btnUsuarioLayout);
        btnUsuarioLayout.setHorizontalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUsuarioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnUsuarioLayout.setVerticalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUsuarioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        sideMenuBg.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 390, -1));

        btnMateria.setBackground(new java.awt.Color(157, 179, 204));

        btnMateriaTxt.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnMateriaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMateriaTxt.setText("Materia");
        btnMateriaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMateriaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMateriaTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMateriaTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMateriaTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMateriaLayout = new javax.swing.GroupLayout(btnMateria);
        btnMateria.setLayout(btnMateriaLayout);
        btnMateriaLayout.setHorizontalGroup(
            btnMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMateriaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnMateriaLayout.setVerticalGroup(
            btnMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMateriaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        sideMenuBg.add(btnMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 390, -1));

        btnTarea.setBackground(new java.awt.Color(157, 179, 204));

        btnTareaTxt.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnTareaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTareaTxt.setText("Tarea");
        btnTareaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTareaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTareaTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTareaTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTareaTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTareaLayout = new javax.swing.GroupLayout(btnTarea);
        btnTarea.setLayout(btnTareaLayout);
        btnTareaLayout.setHorizontalGroup(
            btnTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTareaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnTareaLayout.setVerticalGroup(
            btnTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTareaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        sideMenuBg.add(btnTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 390, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo_white26.png"))); // NOI18N
        jLabel1.setToolTipText("");
        sideMenuBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 160, 110));

        bg.add(sideMenuBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 490));

        bgUserData.setBackground(new java.awt.Color(253, 253, 253));
        bgUserData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        nombreTitleTxt.setText("Nombres");
        bgUserData.add(nombreTitleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRol.setText("Administrador");
        bgUserData.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));
        bgUserData.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 310, 10));
        bgUserData.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 310, 10));

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidos.setText("Zambrano Avila");
        bgUserData.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        apellidosTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        apellidosTitleTxt.setText("Apellidos");
        bgUserData.add(apellidosTitleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        bgUserData.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 310, 10));

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedula.setText("0954887722");
        bgUserData.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        cedulaTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cedulaTitleTxt.setText("Cédula");
        bgUserData.add(cedulaTitleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        bgUserData.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 310, 10));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setText("jczambrano@hotmail.com");
        bgUserData.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        correoTitleTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        correoTitleTxt.setText("Correo electrónico");
        bgUserData.add(correoTitleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtNombres1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombres1.setText("Juan Carlos");
        bgUserData.add(txtNombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user_gray20.png"))); // NOI18N
        bgUserData.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 90, 70));

        bg.add(bgUserData, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 370, 410));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnUsuarioTxtMouseEntered

        btnUsuario.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnUsuarioTxtMouseEntered

    private void btnUsuarioTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnUsuarioTxtMouseExited
        // reestablecer original
        btnUsuario.setBackground(new Color(157, 179, 204));
        btnUsuarioTxt.setForeground(Color.black);
    }// GEN-LAST:event_btnUsuarioTxtMouseExited

    private void btnMateriaTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnMateriaTxtMouseEntered
        btnMateria.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnMateriaTxtMouseEntered

    private void btnMateriaTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnMateriaTxtMouseExited
        // reestablecer original
        btnMateria.setBackground(new Color(157, 179, 204));
    }// GEN-LAST:event_btnMateriaTxtMouseExited

    private void btnTareaTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnTareaTxtMouseEntered
        btnTarea.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnTareaTxtMouseEntered

    private void btnTareaTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnTareaTxtMouseExited
        // reestablecer original
        btnTarea.setBackground(new Color(157, 179, 204));
    }// GEN-LAST:event_btnTareaTxtMouseExited

    private void btnCerrarSesionTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCerrarSesionTxtMouseEntered
        btnCerrarSesion.setBackground(new Color(232, 17, 35));
        btnCerrarSesionTxt.setForeground(Color.white);
    }// GEN-LAST:event_btnCerrarSesionTxtMouseEntered

    private void btnCerrarSesionTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCerrarSesionTxtMouseExited
        // reestablecer original
        btnCerrarSesion.setBackground(new Color(157, 179, 204));
        btnCerrarSesionTxt.setForeground(Color.black);
    }// GEN-LAST:event_btnCerrarSesionTxtMouseExited

    private void btnCerrarSesionTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCerrarSesionTxtMouseClicked

        // temporal
        System.exit(0);
    }// GEN-LAST:event_btnCerrarSesionTxtMouseClicked

    private void btnUsuarioTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnUsuarioTxtMouseClicked
        FrmUserMain frm = new FrmUserMain(this, true);
        frm.setVisible(true);
    }// GEN-LAST:event_btnUsuarioTxtMouseClicked

    private void btnMateriaTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnMateriaTxtMouseClicked
        FrmMatMain frm = new FrmMatMain(this, true);
        frm.setVisible(true);
    }// GEN-LAST:event_btnMateriaTxtMouseClicked

    private void btnTareaTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnTareaTxtMouseClicked
        FrmTareasMain frm = new FrmTareasMain(this, true);
        frm.setVisible(true);
    }// GEN-LAST:event_btnTareaTxtMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidosTitleTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgUserData;
    private javax.swing.JPanel btnCerrarSesion;
    private javax.swing.JLabel btnCerrarSesionTxt;
    private javax.swing.JPanel btnMateria;
    private javax.swing.JLabel btnMateriaTxt;
    private javax.swing.JPanel btnTarea;
    private javax.swing.JLabel btnTareaTxt;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JLabel btnUsuarioTxt;
    private javax.swing.JLabel cedulaTitleTxt;
    private javax.swing.JLabel correoTitleTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel nombreTitleTxt;
    private javax.swing.JPanel sideMenuBg;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtNombres1;
    private javax.swing.JLabel txtRol;
    // End of variables declaration//GEN-END:variables
}
