
package com.ug.ui;

import java.awt.Color;

/**
 *
 * @author Luis
 */
public class FrmAddEditMateria extends javax.swing.JDialog {

    private boolean agregar; // controlar tipo de form (agregar o modificar)

    /**
     * Creates new form FrmAddEditUser
     */
    public FrmAddEditMateria(java.awt.Dialog parent, boolean modal, boolean agregar) {
        super(parent, modal);
        this.agregar = agregar;
        initComponents();

        formSetup();
    }

    private void formSetup() {
        if (agregar) { // si es llamado como form agregar
            setTitle("Agregar Materia");
            btnGuardarTxt.setText("Guardar");
            frmTitle.setText("Agregar Materia");
        } else {
            setTitle("Modificar Materia");
            btnGuardarTxt.setText("Modificar");
            frmTitle.setText("Modificar Materia");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        frmBG = new javax.swing.JPanel();
        nombreTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        nombMatPlaceholder = new javax.swing.JLabel();
        semestrePlaceholder = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        descPlaceholder = new javax.swing.JLabel();
        credPlaceholder = new javax.swing.JLabel();
        modPlaceholder = new javax.swing.JLabel();
        cmbModalidad = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTxt = new javax.swing.JTextArea();
        semestreTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        creditosTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        frmTitle = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        btnGuardarTxt = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        btnCancelarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(62, 88, 121));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frmBG.setBackground(new java.awt.Color(255, 255, 255));
        frmBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(49, 49, 49));
        nombreTxt.setBorder(null);
        frmBG.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, 40));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 10));

        nombMatPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombMatPlaceholder.setText("Nombre");
        frmBG.add(nombMatPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        semestrePlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        semestrePlaceholder.setText("Semestre");
        frmBG.add(semestrePlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 20));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 10));

        descPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descPlaceholder.setText("Descripción");
        frmBG.add(descPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        credPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        credPlaceholder.setText("Créditos");
        frmBG.add(credPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 20));

        modPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modPlaceholder.setText("Modalidad");
        frmBG.add(modPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 20));

        cmbModalidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbModalidad.setForeground(new java.awt.Color(49, 49, 49));
        cmbModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Seleccione...", "Presencial", "Hibrida", "Virtual" }));
        cmbModalidad.setToolTipText("");
        cmbModalidad.setBorder(null);
        frmBG.add(cmbModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 260, 30));

        descripcionTxt.setColumns(20);
        descripcionTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descripcionTxt.setForeground(new java.awt.Color(49, 49, 49));
        descripcionTxt.setLineWrap(true);
        descripcionTxt.setRows(5);
        descripcionTxt.setBorder(null);
        jScrollPane2.setViewportView(descripcionTxt);

        frmBG.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 340, 120));

        semestreTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        semestreTxt.setForeground(new java.awt.Color(49, 49, 49));
        semestreTxt.setBorder(null);
        frmBG.add(semestreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 260, 40));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 260, 10));

        creditosTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        creditosTxt.setForeground(new java.awt.Color(49, 49, 49));
        creditosTxt.setBorder(null);
        frmBG.add(creditosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 260, 40));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 260, 10));

        bg.add(frmBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 300));

        frmTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frmTitle.setForeground(new java.awt.Color(255, 255, 255));
        frmTitle.setText("Agregar Materia");
        bg.add(frmTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        btnGuardar.setBackground(new java.awt.Color(157, 179, 204));

        btnGuardarTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnGuardarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarTxt.setText("Guardar");
        btnGuardarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
                btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardarTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE));
        btnGuardarLayout.setVerticalGroup(
                btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE));

        bg.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 190, 30));

        btnCancelar.setBackground(new java.awt.Color(157, 179, 204));

        btnCancelarTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCancelarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarTxt.setText("Cancelar");
        btnCancelarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
                btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelarTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE));
        btnCancelarLayout.setVerticalGroup(
                btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE));

        bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 190, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_btnGuardarTxtMouseClicked

    private void btnGuardarTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseEntered
        // color resalte
        btnGuardar.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnGuardarTxtMouseEntered

    private void btnGuardarTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseExited
        // reestablecer color original
        btnGuardar.setBackground(new Color(157, 179, 204));
        btnGuardarTxt.setForeground(Color.black);
    }// GEN-LAST:event_btnGuardarTxtMouseExited

    private void btnCancelarTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseClicked
        // temporal
        this.dispose();
    }// GEN-LAST:event_btnCancelarTxtMouseClicked

    private void btnCancelarTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseEntered
        // color resalte
        btnCancelar.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnCancelarTxtMouseEntered

    private void btnCancelarTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseExited
        // reestablecer color original
        btnCancelar.setBackground(new Color(157, 179, 204));
    }// GEN-LAST:event_btnCancelarTxtMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JLabel btnCancelarTxt;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JLabel btnGuardarTxt;
    private javax.swing.JComboBox<String> cmbModalidad;
    private javax.swing.JLabel credPlaceholder;
    private javax.swing.JTextField creditosTxt;
    private javax.swing.JLabel descPlaceholder;
    private javax.swing.JTextArea descripcionTxt;
    private javax.swing.JPanel frmBG;
    private javax.swing.JLabel frmTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel modPlaceholder;
    private javax.swing.JLabel nombMatPlaceholder;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel semestrePlaceholder;
    private javax.swing.JTextField semestreTxt;
    // End of variables declaration//GEN-END:variables

}
