
package com.ug.ui;

import java.awt.Color;

/**
 *
 * @author Luis
 */
public class FrmAddEditTarea extends javax.swing.JDialog {

    private boolean agregar; // controlar tipo de form (agregar o modificar)

    /**
     * Creates new form FrmAddEditUser
     */
    public FrmAddEditTarea(java.awt.Dialog parent, boolean modal, boolean agregar) {
        super(parent, modal);
        this.agregar = agregar;
        initComponents();

        formSetup();
    }

    private void formSetup() {
        if (agregar) { // si es llamado como form agregar
            setTitle("Agregar Tarea");
            btnGuardarTxt.setText("Guardar");
            frmTitle.setText("Agregar Tarea");
        } else {
            setTitle("Modificar Tarea");
            btnGuardarTxt.setText("Modificar");
            frmTitle.setText("Modificar Tarea");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        frmBG = new javax.swing.JPanel();
        tituloTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        titPlaceholder = new javax.swing.JLabel();
        apertPlaceholder = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        descPlaceholder = new javax.swing.JLabel();
        vencPlaceholder = new javax.swing.JLabel();
        corrPlaceholder = new javax.swing.JLabel();
        cmbMaterias = new javax.swing.JComboBox<>();
        dtcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        dtcFechaApertura1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTxt = new javax.swing.JTextArea();
        frmTitle = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        btnGuardarTxt = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        btnCancelarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(62, 88, 121));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frmBG.setBackground(new java.awt.Color(255, 255, 255));
        frmBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tituloTxt.setForeground(new java.awt.Color(49, 49, 49));
        tituloTxt.setBorder(null);
        frmBG.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, 40));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 10));

        titPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titPlaceholder.setText("Título");
        frmBG.add(titPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        apertPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apertPlaceholder.setText("Fecha de apertura");
        frmBG.add(apertPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 20));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 10));

        descPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descPlaceholder.setText("Descripción");
        frmBG.add(descPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        vencPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vencPlaceholder.setText("Fecha de vencimiento");
        frmBG.add(vencPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 20));

        corrPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        corrPlaceholder.setText("Materia");
        frmBG.add(corrPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 20));

        cmbMaterias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMaterias.setForeground(new java.awt.Color(49, 49, 49));
        cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Seleccione...", "Diseño UX", "Marco legal", "Metodología I", "Finanzas" }));
        cmbMaterias.setToolTipText("");
        cmbMaterias.setBorder(null);
        frmBG.add(cmbMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 260, 30));

        dtcFechaVencimiento.setForeground(new java.awt.Color(49, 49, 49));
        dtcFechaVencimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frmBG.add(dtcFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 240, 30));

        dtcFechaApertura1.setForeground(new java.awt.Color(49, 49, 49));
        dtcFechaApertura1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frmBG.add(dtcFechaApertura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 240, 30));

        descripcionTxt.setColumns(20);
        descripcionTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descripcionTxt.setForeground(new java.awt.Color(49, 49, 49));
        descripcionTxt.setLineWrap(true);
        descripcionTxt.setRows(5);
        descripcionTxt.setBorder(null);
        jScrollPane2.setViewportView(descripcionTxt);

        frmBG.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 340, 120));

        bg.add(frmBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 300));

        frmTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frmTitle.setForeground(new java.awt.Color(255, 255, 255));
        frmTitle.setText("Agregar Tarea");
        bg.add(frmTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        btnGuardar.setBackground(new java.awt.Color(157, 179, 204));

        btnGuardarTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnGuardarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarTxt.setText("Guardar");
        btnGuardarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
                btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardarTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE));
        btnGuardarLayout.setVerticalGroup(
                btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE));

        bg.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 190, 30));

        btnCancelar.setBackground(new java.awt.Color(157, 179, 204));

        btnCancelarTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCancelarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarTxt.setText("Cancelar");
        btnCancelarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
                btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelarTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE));
        btnCancelarLayout.setVerticalGroup(
                btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE));

        bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 190, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_btnGuardarTxtMouseClicked

    private void btnGuardarTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseEntered
        // color resalte
        btnGuardar.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnGuardarTxtMouseEntered

    private void btnGuardarTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseExited
        // reestablecer color original
        btnGuardar.setBackground(new Color(157, 179, 204));
        btnGuardarTxt.setForeground(Color.black);
    }// GEN-LAST:event_btnGuardarTxtMouseExited

    private void btnCancelarTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseClicked
        // temporal
        this.dispose();
    }// GEN-LAST:event_btnCancelarTxtMouseClicked

    private void btnCancelarTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseEntered
        // color resalte
        btnCancelar.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnCancelarTxtMouseEntered

    private void btnCancelarTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseExited
        // reestablecer color original
        btnCancelar.setBackground(new Color(157, 179, 204));
    }// GEN-LAST:event_btnCancelarTxtMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apertPlaceholder;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JLabel btnCancelarTxt;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JLabel btnGuardarTxt;
    private javax.swing.JComboBox<String> cmbMaterias;
    private javax.swing.JLabel corrPlaceholder;
    private javax.swing.JLabel descPlaceholder;
    private javax.swing.JTextArea descripcionTxt;
    private com.toedter.calendar.JDateChooser dtcFechaApertura1;
    private com.toedter.calendar.JDateChooser dtcFechaVencimiento;
    private javax.swing.JPanel frmBG;
    private javax.swing.JLabel frmTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel titPlaceholder;
    private javax.swing.JTextField tituloTxt;
    private javax.swing.JLabel vencPlaceholder;
    // End of variables declaration//GEN-END:variables

}
