
package com.ug.ui;

import java.awt.Color;

/**
 *
 * @author Luis
 */
public class FrmAddEditUser extends javax.swing.JDialog {

    private boolean agregar; // controlar tipo de form (agregar o modificar)

    /**
     * Creates new form FrmAddEditUser
     */
    public FrmAddEditUser(java.awt.Dialog parent, boolean modal, boolean agregar) {
        super(parent, modal);
        this.agregar = agregar;
        initComponents();

        formSetup();
    }

    private void formSetup() {
        if (agregar) { // si es llamado como form agregar
            setTitle("Agregar Usuario");
            btnGuardarTxt.setText("Guardar");
            frmTitle.setText("Agregar Usuario");
        } else {
            setTitle("Modificar Usuario");
            btnGuardarTxt.setText("Modificar");
            frmTitle.setText("Modificar Usuario");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        frmBG = new javax.swing.JPanel();
        nombresTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        nmbPlaceholder = new javax.swing.JLabel();
        apellidosTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        aplPlaceholder = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cedPlaceholder = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        telefonoTxt = new javax.swing.JTextField();
        tflPlaceholder = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        correoTxt = new javax.swing.JTextField();
        corrPlaceholder = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        edadTxt = new javax.swing.JTextField();
        edadPlaceholder = new javax.swing.JLabel();
        rolPlaceholder = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        frmTitle = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        btnGuardarTxt = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        btnCancelarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(62, 88, 121));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frmBG.setBackground(new java.awt.Color(255, 255, 255));
        frmBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombresTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombresTxt.setForeground(new java.awt.Color(49, 49, 49));
        nombresTxt.setBorder(null);
        frmBG.add(nombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, 40));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 10));

        nmbPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nmbPlaceholder.setText("Nombres");
        frmBG.add(nmbPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        apellidosTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellidosTxt.setForeground(new java.awt.Color(49, 49, 49));
        apellidosTxt.setBorder(null);
        frmBG.add(apellidosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 260, 40));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 260, 10));

        aplPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aplPlaceholder.setText("Apellidos");
        frmBG.add(aplPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 20));

        cedulaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cedulaTxt.setForeground(new java.awt.Color(49, 49, 49));
        cedulaTxt.setBorder(null);
        frmBG.add(cedulaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 40));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 260, 10));

        cedPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cedPlaceholder.setText("Cédula");
        frmBG.add(cedPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 260, 10));

        telefonoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefonoTxt.setForeground(new java.awt.Color(49, 49, 49));
        telefonoTxt.setBorder(null);
        frmBG.add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 260, 40));

        tflPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tflPlaceholder.setText("Teléfono");
        frmBG.add(tflPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 20));

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 10));

        correoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        correoTxt.setForeground(new java.awt.Color(49, 49, 49));
        correoTxt.setBorder(null);
        frmBG.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 40));

        corrPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        corrPlaceholder.setText("Correo electrónico");
        frmBG.add(corrPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        frmBG.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 160, 10));

        edadTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edadTxt.setForeground(new java.awt.Color(49, 49, 49));
        edadTxt.setBorder(null);
        frmBG.add(edadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 160, 40));

        edadPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edadPlaceholder.setText("Edad");
        frmBG.add(edadPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, 20));

        rolPlaceholder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rolPlaceholder.setText("Rol");
        frmBG.add(rolPlaceholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, 20));

        cmbRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRol.setForeground(new java.awt.Color(49, 49, 49));
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Seleccione...", "Administrador", "Estudiante", "Docente" }));
        cmbRol.setToolTipText("");
        cmbRol.setBorder(null);
        frmBG.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 160, 30));

        bg.add(frmBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 300));

        frmTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frmTitle.setForeground(new java.awt.Color(255, 255, 255));
        frmTitle.setText("Agregar Usuario");
        bg.add(frmTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        btnGuardar.setBackground(new java.awt.Color(157, 179, 204));

        btnGuardarTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnGuardarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarTxt.setText("Guardar");
        btnGuardarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
                btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardarTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE));
        btnGuardarLayout.setVerticalGroup(
                btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE));

        bg.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 190, 30));

        btnCancelar.setBackground(new java.awt.Color(157, 179, 204));

        btnCancelarTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCancelarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarTxt.setText("Cancelar");
        btnCancelarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
                btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelarTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE));
        btnCancelarLayout.setVerticalGroup(
                btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE));

        bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 190, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_btnGuardarTxtMouseClicked

    private void btnGuardarTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseEntered
        // color resalte
        btnGuardar.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnGuardarTxtMouseEntered

    private void btnGuardarTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarTxtMouseExited
        // reestablecer color original
        btnGuardar.setBackground(new Color(157, 179, 204));
        btnGuardarTxt.setForeground(Color.black);
    }// GEN-LAST:event_btnGuardarTxtMouseExited

    private void btnCancelarTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseClicked
        // temporal
        this.dispose();
    }// GEN-LAST:event_btnCancelarTxtMouseClicked

    private void btnCancelarTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseEntered
        // color resalte
        btnCancelar.setBackground(new Color(185, 201, 219));
    }// GEN-LAST:event_btnCancelarTxtMouseEntered

    private void btnCancelarTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCancelarTxtMouseExited
        // reestablecer color original
        btnCancelar.setBackground(new Color(157, 179, 204));
    }// GEN-LAST:event_btnCancelarTxtMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTxt;
    private javax.swing.JLabel aplPlaceholder;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JLabel btnCancelarTxt;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JLabel btnGuardarTxt;
    private javax.swing.JLabel cedPlaceholder;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel corrPlaceholder;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JLabel edadPlaceholder;
    private javax.swing.JTextField edadTxt;
    private javax.swing.JPanel frmBG;
    private javax.swing.JLabel frmTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nmbPlaceholder;
    private javax.swing.JTextField nombresTxt;
    private javax.swing.JLabel rolPlaceholder;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel tflPlaceholder;
    // End of variables declaration//GEN-END:variables

}
