
package com.ug.ui;

import java.awt.Color;

/**
 *
 * @author Luis
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        contrasenaTxt = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JPanel();
        btnIngresarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UG Tasks - Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(62, 88, 121));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("UG Tasks");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        usuarioTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioTxt.setForeground(new java.awt.Color(204, 204, 204));
        usuarioTxt.setText("Usuario");
        usuarioTxt.setBorder(null);
        usuarioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioTxtMousePressed(evt);
            }
        });
        jPanel1.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 260, 40));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 260, 10));

        contrasenaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contrasenaTxt.setForeground(new java.awt.Color(204, 204, 204));
        contrasenaTxt.setText("..........");
        contrasenaTxt.setBorder(null);
        contrasenaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaTxtMousePressed(evt);
            }
        });
        jPanel1.add(contrasenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 260, 30));

        btnIngresar.setBackground(new java.awt.Color(62, 88, 121));
        btnIngresar.setForeground(new java.awt.Color(62, 88, 121));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnIngresarTxt.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnIngresarTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresarTxt.setText("Ingresar");
        btnIngresarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarTxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnIngresarLayout = new javax.swing.GroupLayout(btnIngresar);
        btnIngresar.setLayout(btnIngresarLayout);
        btnIngresarLayout.setHorizontalGroup(
                btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnIngresarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE));
        btnIngresarLayout.setVerticalGroup(
                btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnIngresarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 260, 40));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 470, 450));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarTxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnIngresarTxtMouseEntered
        // color para darle resalto
        btnIngresar.setBackground(new Color(72, 103, 140));
    }// GEN-LAST:event_btnIngresarTxtMouseEntered

    private void btnIngresarTxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnIngresarTxtMouseExited
        // color original rgb
        btnIngresar.setBackground(new Color(62, 88, 121));
    }// GEN-LAST:event_btnIngresarTxtMouseExited

    private void btnIngresarTxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnIngresarTxtMouseClicked
        // logica login

        dispose();
        FrmMainMenu frm = new FrmMainMenu(this, true);
        frm.setVisible(true);
        // incluir esto al final para restablecer placeholders
        usuarioTxt.setText("Usuario");
        contrasenaTxt.setText("..........");
    }// GEN-LAST:event_btnIngresarTxtMouseClicked

    private void usuarioTxtMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_usuarioTxtMousePressed
        if (usuarioTxt.getText().equals("Usuario")) {
            usuarioTxt.setText("");
            usuarioTxt.setForeground(Color.black);
        }
    }// GEN-LAST:event_usuarioTxtMousePressed

    private void contrasenaTxtMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_contrasenaTxtMousePressed
        if (String.valueOf(contrasenaTxt.getPassword()).equals("..........")) {
            contrasenaTxt.setText("");
            contrasenaTxt.setForeground(Color.black);
        }
    }// GEN-LAST:event_contrasenaTxtMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnIngresar;
    private javax.swing.JLabel btnIngresarTxt;
    private javax.swing.JPasswordField contrasenaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
